---

- hosts: all
  become: true
  tasks: 

  - name: install nginx package # this could be any name
    apt:                        # this is module (-m)
      name: nginx               # this is arg (-a)
      state: latest
      update_cache: yes         # run apt update
    when: ansible_distribution == "Ubuntu"  # condition to only apply if OS is Ubuntu
  - name: start nginx
    shell: |
      systemctl start nginx
    when: ansible_distribution in  ["Debian", "Ubuntu"] # list variables, this is like OR operation. 

